### ISSUE TITLE
Role of DNA

### ISSUE THREAD

**Issue by ya1gaurav** [distributedweaknessfiling/DNA-Registry#4]
I have below queries:
1. DWF is to replace CVE?
2. Who will review reported DWF? as CVEs are reviewed.
3. Why 2 databases CVE & DWF?
4. Is there mutual understanding between CVE Mitre's authority & DNA?

**Comment by kurtseifried** [comment]
> I have below queries:
> 1. DWF is to replace CVE?

That is up to the community.

> 2. Who will review reported DWF? as CVEs are reviewed.

What do you mean by reviewed? You mean CVE style write ups? That's mostly already done by the community, e.g. most vendors provide security reports with far more details, for example OpenStack: https://security.openstack.org/ossalist.html or ruby on rails: https://groups.google.com/forum/#!forum/rubyonrails-security

Also if the community really wants these CVE style writeups people can research them and write them up and submit them and we'll be happy to take them. 

> 3. Why 2 databases CVE & DWF?

CVE is one database, controlled by Mitre. DWF is a separate Database, controlled by the DWF project. Mitre does not accept external data as far as I know. The DWF does accept external data, happily!
 
> 4. Is there mutual understanding between CVE Mitre's authority & DNA?

No, that's part of the problem, Mitre has stopped responding to people, security researchers and board members alike:

https://cve.mitre.org/data/board/archives/2016-03/msg00006.html
https://cve.mitre.org/data/board/archives/2016-03/msg00000.html

In my role as a board member I did post this:

http://common-vulnerabilities-and-exposures-cve-editorial-board.1128451.n5.nabble.com/Regarding-the-Distributed-Weakness-Filing-system-td123.html

**Comment by ya1gaurav** [comment]
`Who will review reported DWF? as CVEs are reviewed.`
dfdf

**Comment by ya1gaurav** [comment]
One more question, if an OpenSource is inactive means there is no fix in past many years and some guy reports a vulnerability issue. In this case DWF will be assigned only if there is proposed fix? or DNA will propose a fix which others can apply?
Since the fix cannot be applied to main branch as it is inactive, will a proposed fix be available on DWF github post publically?
Is there any proposal for this kind of situations? it simply will help users from wandering here and there for confirm fix.
